### DISCUSSION TITLE
I can't seem to get OAuth2/OIDC working - missing access_token

### DISCUSSION THREAD

**Discussion by yaakov-h** [kanidm/kanidm#2058] [Q&A] [answered]
I've managed to get kanidm server up and running and tried to use it as the IDP for two applications - Gitea, and Grafana.

When I try log in to Gitea, I get the following error:

> 2023/09/03 08:33:53 ...rs/web/auth/oauth.go:939:SignInOAuthCallback() [E] UserSignIn: oauth2: server response missing access_token

When I try log in to Grafana, I get the following error:

> logger=authn.service t=2023-09-03T06:57:28.325212504Z level=warn msg="Failed to authenticate request" client=auth.client.generic_oauth error="[auth.oauth.token.exchange] failed to exchange code to token: oauth2: server response missing access_token"

There is this issue (https://github.com/go-gitea/gitea/issues/26429) open with Gitea, which is why I then thought I'd try a different application, but the similarity of both error messages to me suggests that they might be using the same library for this.

I'm running Kanidm beta 13 as a container inside a single-node K3S Kubernetes installation behind Traefik. Grafana is in the same installation, whereas Gitea is on another server inside a similar single-node Microk8s installation behind Nginx. 

Here's my configuration for Gitea in kanidm. I tried starting to define admin rights via a group in Kanidm, but haven't gotten far enough see if that works:

```plain
class: oauth2_resource_server
class: oauth2_resource_server_basic
class: object
displayname: Gitea
es256_private_key_der: private_binary
oauth2_allow_insecure_client_disable_pkce: true
oauth2_prefer_short_username: false
oauth2_rs_basic_secret: hidden
oauth2_rs_name: gitea
oauth2_rs_origin: https://gitea.yaakov.dev/
oauth2_rs_origin_landing: https://gitea.yaakov.dev/user/oauth2/kanidm
oauth2_rs_scope_map: gitea_admins@clanker.yaakov.online: {"admin"}
oauth2_rs_scope_map: gitea_users@clanker.yaakov.online: {"email", "openid"}
oauth2_rs_token_key: hidden
```

and then in Gitea's Authentication Sources admin panel, I've set it up using OpenID Connect as the OAuth 2 Provider, set `gitea` as the Client ID, and set both the Client Secret and OpenID Connect Auto Discovery URL.

For Grafana I have a simpler config (so far) with just one group defined for access:

```plain
class: oauth2_resource_server
class: oauth2_resource_server_basic
class: object
displayname: Grafana
es256_private_key_der: private_binary
oauth2_rs_basic_secret: hidden
oauth2_rs_name: grafana
oauth2_rs_origin: https://grafana.yaakov.online/
oauth2_rs_origin_landing: https://grafana.yaakov.online/login/generic_oauth
oauth2_rs_scope_map: grafana_users@clanker.yaakov.online: {"email", "openid", "profile"}
oauth2_rs_token_key: hidden
```

and then in Grafana I've configured everything via environment variables:

```yaml
env:
- name: GF_SERVER_ROOT_URL
  value: 'https://grafana.yaakov.online/'
- name: GF_AUTH_GENERIC_OAUTH_ENABLED
  value: 'true'
- name: GF_AUTH_GENERIC_OAUTH_NAME
  value: Kanidm
- name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
  value: grafana
- name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
  valueFrom:
    secretKeyRef:
      name: grafana-oauth
      key: client_secret
- name: GF_AUTH_GENERIC_OAUTH_SCOPES
  value: 'openid email profile'
- name: GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH
  value: 'preferred_username'
- name: GF_AUTH_GENERIC_OAUTH_AUTH_URL
  value: 'https://clanker.yaakov.online/ui/oauth2'
- name: GF_AUTH_GENERIC_OAUTH_TOKEN_URL
  value: 'https://clanker.yaakov.online/oauth2/token'
- name: GF_AUTH_GENERIC_OAUTH_API_URL
  value: 'https://clanker.yaakov.online/oauth2/openid/grafana/userinfo'
- name: GF_AUTH_GENERIC_OAUTH_USE_PKCE
  value: 'true'
```

I've double-checked my work against both the Kanidm book as well as [this blog post by Ashley](https://ashhhleyyy.dev/blog/2023-02-05-from-keycloak-to-kanidm) but I can't find any obvious discrepancies.

Any suggestions for where I've gone wrong or how to troubleshoot this?
