### DISCUSSION TITLE
Docker compose based installation

### DISCUSSION THREAD

**Discussion by compgeniuses** [kanidm/kanidm#2583] [Ideas]
Is there or would there be a proper docker compose based installation support for KanIDM on a prodcution sytem?

**Comment by yaleman** [comment]
It's a single container, so something like this should do:

```yaml
---
version: "3.5"

services:
  kanidmd:
    container_name: kanidmd
    restart: "always"
    image: kanidm/server:latest
    volumes:
      - type: bind
        source: /etc/kanidm/
        target: /data/
      - "kanidm_data:/var/lib/kanidm/"
    ports:
      - "443:8443"
volumes:
  kanidm_data:
```

This assumes a couple of things:

1. Your certs are in `/etc/kanidm` on the host machine, the config refers to them from that point.
2. You've got a `server.toml` file in `/etc/kanidm/server.toml`

On my docker-compose'd set up I use `network_mode: host` instead of port mapping because I want to see client IPs.
