### DISCUSSION TITLE
Kandim server not displaying in browser

### DISCUSSION THREAD

**Discussion by D3an1el** [kanidm/kanidm#2801] [Q&A] [answered]
Hi, got an issue where  Kandim server logs say its running, but its a blank screen in the browser. i have made the owner of the `./data` folder as 1001. I  also have caddy setup, 
```
ｉ [info]: ready to rock! 🪨  UI available at: https://idm.example.io
```

The only odd thing in the logs, which i dont understand as it is the owner of the `./data` folder and has RW permissions

```
🚧 [warn]: This is running as uid == 0 (root) which may be a security risk.
🚧 [warn]: WARNING: DB folder permissions on /data indicate it may not be RW. This could cause the server start up to fail!
```

Docker compose file used:
```
version: "3.9"
services:
  kanidm-server:
    container_name: kanidm-server
    image:  kanidm/server:1.2.0
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
    ports:
      - "8443:8443"
    volumes:
      - ./data:/data
```

CADDYFILE: selfsigned fullchain certs

```
idm.example.io. {
        tls /etc/caddy/ssl/full-chain-bundle-idm.cert.pem /etc/caddy/ssl/idm.example.io.key.password-less.pem
        reverse_proxy https://127.0.0.1:8443

        tls {
                protocols tls1.2 tls1.3
                ciphers TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 TLS_ECDHE_R>
        }

        log {
                output file /var/log/caddy/idm-access.log {
                        level infoo
                        roll_size 10mb
                        roll_keep 20
                        roll_keep_for 720h
		}
	}
}
```
