### DISCUSSION TITLE
kanidm on docker swarm behind traefik

### DISCUSSION THREAD

**Discussion by ieugen** [kanidm/kanidm#2902] [Show and tell]
hi, 

I've deployed kanidm 1.2.3 behind traefik 3 proxy using letsencrypt TLS .
Need to test LDAP as well, but http auth works via UI and cli. 

- I created my own CA and certs for kanidm to host on TLS
- I am using LetsEncrypt certs via Traefik - which handles TLS termination.
- tls connection from traefik to kanidm using skipverify - I could add the CA and check this cert, but I am lazy

Used this for CA creation, but you can use any tool or a self signed certificate:
https://github.com/lechgu/tinyca .
Created a chain using the method described in the issue: https://github.com/lechgu/tinyca/issues/6  .

server.toml
```toml
bindaddress = "[::]:8443"
ldapbindaddress = "[::]:3636"
trust_x_forward_for = true
db_path = "/data/kanidm.db"
tls_chain = "/data/chain.pem"
tls_key = "/data/key.pem"

domain = "idm.example.com"
origin = "https://idm.example.com"
[online_backup]
path = "/kanidm-backups/"
schedule = "0 0 22 * * *"
```

I have configured traefik in docker swarm and for kanidm we need to setup a `serverTransport` that disables TLS check between traefik -> kanidm. 

This needs to be done via file provider - dynamic configuration https://doc.traefik.io/traefik/routing/services/#serverstransport_1 . 
You can't configure a server transport via docker swarm labels. 

traefik/dynamic.yml
```yaml


http:
  serversTransports:
    kanidm:
      insecureSkipVerify: true

  middlewares:
    # https-redirect middleware to redirect HTTP to HTTPS
    # It can be re-used by other stacks via https-redirect@file
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    auth-headers:
      headers:
        stsSeconds: 315360000
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        # sslHost: example.com
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true

``` 

Next is the kanidm deployment.
We reference the server transport by name.

```yaml

version: "3.9"
services:

  kanidm:
    image: "docker.io/kanidm/server:1.2.3"
    #environment:
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 0
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 128m
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.hostname == xxx"
      labels:
        traefik.enable: "true"
        traefik.docker.network: traefik-public
        traefik.constraint-label: traefik-public
        # http
        traefik.http.routers.kanidm-http.entrypoints: http
        traefik.http.routers.kanidm-http.rule: Host(`idm.example.com`)
        traefik.http.routers.kanidm-http.middlewares: https-redirect@file
        # https
        traefik.http.routers.kanidm-https.entrypoints: https
        traefik.http.routers.kanidm-https.rule: Host(`idm.example.com`)
        traefik.http.routers.kanidm-https.tls: "true"
        traefik.http.routers.kanidm-https.tls.certresolver: le
        traefik.http.services.kanidm.loadbalancer.server.port: 8443
        traefik.http.services.kanidm.loadbalancer.server.scheme: "https"
        traefik.http.services.kanidm.loadbalancer.serversTransport: kanidm@file

    configs:
      - source: server.toml
        target: /data/server.toml
        mode: 0400
    secrets:
      - source: key.pem
        target: /data/key.pem
        mode: 0400
      - source: chain.pem
        target: /data/chain.pem
        mode: 0400
    volumes:
      - /home/docker-volumes/idm/data:/data
      - /home/docker-volumes/idm/backups:/kanidm-backups

# Config and secret names are generated from file hash to be unique (to avoid docker immutable configs issue) 

secrets:
  key.pem:
    # external: true
    file: secrets/key.pem
    name: key.pem_905cfe
  chain.pem:
    file: secrets/chain.pem
    name: chain.pem_85d22d

configs:
  server.toml:
    file: config/server.toml
    name: server.toml_60f9a4

networks:
  traefik-public:
    name: traefik-public
    external: true
```
