### DISCUSSION TITLE
Kanidm setup with Matrix Authentication Service

### DISCUSSION THREAD

**Discussion by Cameo007** [kanidm/kanidm#3072] [Q&A] [answered]
Hi,
I gonna ask here because I cannot use Matrix at the moment.
Did anyone set up Kanidm with the Matrix Authentication Service? They have examples for Authentik or Keycloak but not Kanidm.

This is my MAS config
```
upstream_oauth2:
  providers:
    - id: A_RANDOM_ID
      human_name: mintuxAuth
      issuer: "https://idm.mintux.de/oauth2/openid/matrix"
      token_endpoint_auth_method: client_secret_basic
      client_id: "matrix"
      client_secret: "SOME_SECRET"
      scope: "email openid profile"
```

And here is my Kanidm config
```
class: account
class: memberof
class: oauth2_resource_server
class: oauth2_resource_server_basic
class: object
displayname: Matrix
es256_private_key_der: private_binary
memberof: idm_all_accounts@idm.mintux.de
name: matrix
oauth2_prefer_short_username: true
oauth2_rs_basic_secret: hidden
oauth2_rs_origin: https://mas.mintux.de/upstream/callback/A_RANDOM_ID
oauth2_rs_origin_landing: https://element.mintux.de/
oauth2_rs_scope_map: mintux_matrix@idm.mintux.de: {"email", "openid", "profile"}
oauth2_rs_token_key: hidden
spn: matrix@idm.mintux.de
uuid: xxx-xxx-xxx
```

When signing in I see Kanidm and get then redirected to MAS where it says `wrong signature alg`.
