### DISCUSSION TITLE
kanidm in kubernetes (k3s)

### DISCUSSION THREAD

**Discussion by InukVT** [kanidm/kanidm#3261] [Show and tell]
Hello!

With the help of the fine folks on the community chat I've deployed kanidm in kubernetes. And I'm here to share some of the pitfalls I've found (mostly kubernetes lack of knowledge on my part).

## ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iam-tls-ingress
  namespace: iam
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: idenity.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kanidmd
                port:
                  name: https
  tls:
    - secretName: iam-tls
      hosts:
        - idenity.example.com
```
There's nothing too interesting going on here, but do keep in mind that traefik in k3s handles all traffick on port 443, and will make sure to forward anything to your service's port, even if it isn't port 443 (in my case it was port 8443, ddefault in kanidm)

## service.yaml
```yaml
kind: Service
apiVersion: v1
metadata:
  namespace: iam
  name: kanidmd
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: "iam-servername@kubernetescrd"
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
    traefik.ingress.kubernetes.io/service.serversscheme: "https"
spec:
  selector:
    app: kanidmd
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
```
This is the file I've experience the most skillissues with. Because kanidm uses TLS, you need to make sure that it talks with a traefik, I was unsure how to do this properly, and if I didn't do anything, I would get server errror. Therefore what I did was just skip the TLS check, this needs a ServiceTransport, which we'll get to.

Other than that, originally I ran on `NodePort`, which isn't ideal, and I proxied the kanidm traffic through a nginx server on a different machine, which has since died. Ultimately I prefer this approach of using traefik on my kubernetes cluster, it also makes it much easier to manage TLS.

## servicetransport.yaml
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: servername
  namespace: iam
spec:
  serverName: idenity.example.com
```

~~Because this is a traefik thing and not a kanidm thing, I put it in the same namespace as traefik, which on k3s systems is `kube-system`, this is very unassuming, it's just telling traefik to ignore TLS issues, ideally in the long run I would love to remove this, but that's not where I am right now unfortunately.~~

An updated version of ServerTransport lives in the same namespace as the rest of my kanidm installation. This exposes the services as `idenity.example.com`, making it so I don't have to use insecure skip, which is much sager in case I accidnetally mount the wrong pod in the future.

## storage
```yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: iam
  name: kanidmd-db
spec:
  capacity:
    storage: 2Gi
  storageClassName: kanidm-storage
  accessModes:
    - ReadWriteOnce
  local:
    path: /kubes/kanidmd
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kubes
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: iam
  name: kanidmd-db
spec:
  selector:
    matchLabels:
      pv: kanidmd-db
  accessModes:
    - ReadWriteOnce
  storageClassName: kanidm-storage
  resources:
    requests:
      storage: 2Gi
  volumeName: kanidmd-db
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kanidm-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

The story stuff I just took from elsewhere. My biggest issue with my storage is how it's dependant on one of my notes, here just called `kubes` (creative, I know)

Ideally in the future, I would like to move it to NFS or similar, but that requires time and research.

## deploy.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iam
  name: kanidmd
  labels:
    app: kanidmd
spec:
  selector:
    matchLabels:
      app: kanidmd
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: kanidmd
    spec:
      securityContext:
        runAsGroup: 5000
        runAsUser: 5000
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
      volumes:
        - name: kanidmd-certs
          secret:
            secretName: iam-tls
        - name: kanidmd-db
          persistentVolumeClaim:
            claimName: kanidmd-db
        - name: kanidmd-server-toml
          configMap:
            name: kanidmd-server-toml
            items:
              - key: server.toml
                path: server.toml
        - name: socket-volume
          emptyDir: {}
      containers:
        - name: kanidmd
          image: kanidm/server:1.4.3
          env:
            - name: KANIDM_BINDADDRESS
              value: "[::]:8443"
            - name: KANIDM_DOMAIN
              value: identity.example.com
            - name: KANIDM_ORIGIN
              value: https://identity.example.com:443
            - name: KANIDM_LOG_LEVEL
              value: DEBUG
            - name: KANIDM_ADMIN_BIND_PATH
              value: "/var/run/kanidmd.sock"
            - name: KANIDM_TLS_CHAIN
              value: /certs/tls.crt
            - name: KANIDM_TLS_KEY
              value: /certs/tls.key
            - name: RUST_LOG
              value: DEBUG
          ports:
            - name: https
              containerPort: 8443
            - name: ldaps
              containerPort: 3636
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: kanidmd-db
              mountPath: /db
            - name: kanidmd-server-toml
              mountPath: /data/server.toml
              subPath: server.toml
              readOnly: true
            - name: kanidmd-certs
              readOnly: true
              mountPath: "/certs"
            - name: socket-volume
              mountPath: /var/run
          resources:
            requests:
              memory: 256Mi
              cpu: "250m"
            limits:
              memory: 1536Mi
              cpu: "1"
          livenessProbe:
            httpGet:
              path: /status
              port: https
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
```

Like the storage, this too is mostly unassuming. most of the values are abitrary, or otherwise follows yaleman's template.

## Conclusion

After I got my system to work, I'm very chipper. It's really nice exposing stuff on port 443 natively in kubernetes, and the potential savings in failover is also really nice.

My first integration was with proxmox, and after setting it all it, it was relatively painless.

**Comment by yaleman** [comment]
So to avoid the backend server transport skip-verify TLS you need trusted certs on the Kanidm server and you can set spec.serverName in the transport instead. 

For example, if you have example.com exposed and are mounting the certs that traefik gets for that (which has been the easiest way in my experience) then you set serverName to example.com

**Reply by InukVT** [reply]
Thanks for the headsup, I've updated my show and tell to include what I learned from this!

**Comment by stefan-fast** [comment]
Thanks a lot for sharing this valuable information!

While doing a little setup of my own, I came across some issues and would like to share them and what I did to solve them. Maybe it can help others as well.

First I had issues similar to this one: https://github.com/kanidm/kanidm/issues/2704. Like the comment https://github.com/kanidm/kanidm/issues/2704#issuecomment-2289945025 suggests, the issue was because of a wrong domain used in the frontend. I already setup the origin setting to use my domain.
But when trying to register with a passkey, I was trying to use a port forward to localhost, which caused the origin to be localhost instead of my domain, which caused the registration to fail.
A bit weird that it fails kind of silently in the frontend, but wrong usage on my side, so I can live with that.

When setting up the ingress to actually use the domain, the information here was very helpful.
But: I had kanidm running with 2 replicas, which lead to all sorts of weird issues when trying to register or login.
I'll list the logs, so people having similar issues may find this when using the search:

```
session id not present in cred
```
```
No such sessionid exists on this server
```
```
Failed to begin credential_passkey_finish | err: InvalidRequestState
```
```
INFO     request [ 403µs | 83.92% / 100.00% ] method: POST | uri: /ui/login/passkey | version: HTTP/1.1 | connection_address: "10.244.0.119:53182" | client_address: "10.244.0.119" | status_code: 200 | latency: 0 | kopid: "f7e291b0-643c-44d4-9964-e75f96580ff3"
INFO     ┝━ pre_validate_client_auth_info [ 8.88µs | 1.99% / 2.20% ]
INFO     │  ┕━ validate_client_auth_info_to_uat [ 834ns | 0.21% ]
ERROR    ┝━ 🚨 [error]: Failed to deserialise JWT from request | err: InvalidSignature
WARN     ┝━ 🚧 [warn]: Invalid Signature errors can occur if your instance restarted recently, if a load balancer is not configured for sticky sessions, or a session was tampered with.
INFO     ┕━ auth [ 56.0µs | 13.88% ]
INFO        ┝━ ｉ [info]: Begin auth event | event_tag_id: 10 | sessionid: None | req: Cred(Passkey(_))
ERROR       ┕━ 🚨 [error]: Failed to parse AuthEvent | err: InvalidAuthState("session id not present in cred to 'cred' step")
```

The solution ended up being to use **sticky session cookies** to ensure the same replica is used for the whole login process, which for me mitigated all the issues above. You can enable sticky session cookies with Traefik as ingress controller by setting these annotations on your Kubernetes Service:
```yaml
traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
traefik.ingress.kubernetes.io/service.sticky.cookie.name: "kanidm_sticky_session"
```
so it looks something like this:
```yaml
kind: Service
apiVersion: v1
metadata:
  namespace: kanidm
  name: kanidmd
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    # Naming for referencing the ServersTransport: <namespace>-<servers-transport-name>@kubernetescrd
    traefik.ingress.kubernetes.io/service.serverstransport: kanidm-kanidm-transport@kubernetescrd
    traefik.ingress.kubernetes.io/service.passhostheader: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "kanidm_sticky_session"
spec: ...
```

Interestingly, the documentation [here](https://kanidm.github.io/kanidm/master/repl/index.html#introduction) sounds like sticky sessions are recommended but optional, while in my experience, they are actually required to have a working login and registration process when using multiple replicas.
