### DISCUSSION TITLE
tip on using TLS with cloudflare tunnel in rootless containers

### DISCUSSION THREAD

**Discussion by iridial** [kanidm/kanidm#3455] [Show and tell]
Hello, I read the "Preparing for your Deployment" and "Why TLS?" pages in the docs, it mentions Let's Encrypt and that's a good way to make it work without having to use self-signed certs, however it may not be possible to bind to port 443 of the host when running in a rootless container environment.

I believe is worth mentioning another way of getting the cert if one plans to use the cloudflare tunnel service: generating a CF origin server cert and key, which last for 15 years, and is valid only for traffic between the cloudflared and kanidm. https://developers.cloudflare.com/ssl/origin-configuration/origin-ca/

This is my `docker-compose.yml` file for reference:

```
services:
  kanidm:
    image: kanidm/server:latest
    restart: unless-stopped
    container_name: kanidm
    user: 1000:1000
    environment:
      TZ: UTC
#    open port for debug purposes
#    ports:
#      - 8443:8443
    volumes:
      - kanidm:/data
      - ./kanidm/backups:/backups
    networks:
      - auth

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    env_file: .env_cloudflare
    restart: unless-stopped
    networks:
      - auth

volumes:
  kanidm:
    external: true
    name: kanidmd

networks:
  auth:
```

the `.env_cloudflare` file content is:

```
TUNNEL_TOKEN=<your cf tunnel token>
TZ=UTC
```
Using the base `server.toml` of the docs.

To make the cert validation work, the tunnel must be configured in the cloudflare zero trust dash with "TLS -> Origin Server Name" to one compatible with the generated origin server cert, leaving "No TLS Verify" to false by default.

Hope this can be helpful :)
