### ISSUE TITLE
Please provide kanidm version or git sha or link to git commit for the book 

### ISSUE THREAD

**Issue by ieugen** [kanidm/kanidm#2571]
Hello,

**Is your feature request related to a problem? Please describe.**

I saw there are links to Kanidm book for stable and latest commit (master) in the dev section. 
But there is no information in the book regarding what version of kanidm it applies to.
There is also no date when the book was generated.

I know it mentions `master` but maybe the CI that builds it fails and it's master from 2 months ago (exaggerating).

**Describe the solution you'd like**

I think it would be useful to include in the book some of the following information:
- date when the book was generated
- git sha of the commit that built the book
- git url to the commit (duplicate of the above, but more user friendly)
- Kanidm version that the book applies to. This can be deduced from the commit but it might not be obvious for most people.

**Describe alternatives you've considered**

**Additional context**

**Comment by yaleman** [comment]
By the looks of it, this'll require either:

- a custom mdbook preprocessor or 
- randomly cat'ing things into a markdown file on build?

**Comment by Rushmore75** [comment]
I was going to take a crack at this, but it looks like the docs versions are intentionally not inter-version navigate-able?

https://github.com/kanidm/kanidm/blob/a5fa69ec1a88d9165ac699f53f98237026eda5c7/.github/workflows/kanidm_book.yml#L51
https://github.com/kanidm/kanidm/blob/a5fa69ec1a88d9165ac699f53f98237026eda5c7/.github/workflows/kanidm_book.yml#L73C1-L73C59

The standard index.html file is (essentially) just a large list of every version of the docs. Perhaps we want to bring that back?
It looks like the https://github.com/kanidm/kanidm/blob/master/scripts/build_all_the_docs.sh already generates the solution to this problem.

So it looks like we just need to change the kanidm_book.yml workflow?

**Comment by Rushmore75** [comment]
I'd imagine a workflow like
```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: "github-pages"
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # yamllint disable-line rule:line-length
    if: ${{ github.ref == 'refs/heads/master' && github.repository == 'kanidm/kanidm' }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install Cargo packages
        run: |
          cargo install mdbook
          cargo install mdbook-mermaid
      - name: Build Book
        run: ./scripts/build_all_the_docs.sh
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload pages artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload entire repository
          path: 'docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
would work. (IDK the best way to test gh workflows)
