### ISSUE TITLE
Can't login to instance due to token serialisation issue

### ISSUE THREAD

**Issue by yaleman** [kanidm/kanidm#2740]
### I did this

`kanidm login -D idm_admin` with an empty token file and the following config:

```toml
uri = "https://localhost:8443"
verify_ca = true
ca_path = "/tmp/kanidm/ca.pem"

[test]
uri = "https://foo.com"
```

### I expected the following

It to work, but I got this:

```text
ERROR kanidm_cli::session: JSON/IO error writing tokens to file "/Users/yaleman/.cache/kanidm_tokens" -> Error("key must be a string", line: 0, column: 0)
ERROR kanidm_cli::session: Error persisting authentication token store
```

This was left in `~/.cache/kanidm_tokens`:

```shell
$ cat ~/.cache/kanidm_tokens
{
  "instances": {
    
```

(note the four spaces on the last line, if it matters)

### Kanidm version details

- Output of `kanidm(d) version`: kanidmd 1.2.0-dev a0f743d8c8 / kanidm 1.2.0-dev a0f743d8c8
- Are you running it in a container? If so, which image/tag?: no
- If not a container, how'd you install it: running from git master
- Operating System / Version (On Unix please post the output of `uname -a`): macos
