### ISSUE TITLE
docs: TLS FAQ - Better clarify distinction of TLS requirement for secure cookies

### ISSUE THREAD

**Issue by polarathene** [kanidm/kanidm#2969]
### Is your feature request related to a problem? Please describe

FAQ correction for the docs.

https://github.com/kanidm/kanidm/blob/f1dfbcc25373201b0fd306f0507ad82b9297fb79/book/src/frequently_asked_questions.md?plain=1#L5-L14

https://github.com/kanidm/kanidm/blob/f1dfbcc25373201b0fd306f0507ad82b9297fb79/book/src/frequently_asked_questions.md?plain=1#L27-L31

### Describe the solution you'd like

Update the FAQ entry to not convey that `secure` cookies can only work with kanidm enforcing TLS. It is communicated that the client must use HTTPS with the request, but a reverse proxy that handles the TLS and forwards the request as HTTP to kanidm is still valid.

This is partially addressed by the next FAQ entry, where the motivation for TLS through the full path from client to kanidm is explained:

https://github.com/kanidm/kanidm/blob/f1dfbcc25373201b0fd306f0507ad82b9297fb79/book/src/frequently_asked_questions.md?plain=1#L33-L38

Not here to debate that stance, but the [actual reason that kanidm chooses to enforce TLS](https://github.com/kanidm/kanidm/pull/2950#issuecomment-2267423632) was primarily due to too many users deploying without TLS and being bitten by that. I requested further context on that but was not provided it.

**UPDATE:** Since I started writing this issue up, review feedback was added to https://github.com/kanidm/kanidm/pull/2963 , which includes a suggestion that better communicates this 👍 (_Cookie section still needs to be revised, I've [provided a suggestion](https://github.com/kanidm/kanidm/pull/2963/files#r1713473323) as reference_)

### Describe alternatives you've considered

Not writing up this issue? 😅 

Feel to close. This was just something I wanted to clear up from the discussion I had. The issue itself documents the concern well enough should anyone else find the FAQ reasoning a tad confusing.

### Additional context

While I understand this is a touch subject for the project maintainers (_along with the [pending revision](https://github.com/kanidm/kanidm/pull/2963) to further emphasize the requirement as non-negotiable_), I think it would help avoid confusion when stating TLS must be used with connections to kanidm for this feature to work.

Refusing to acknowledge that or amend the FAQ entry does the opposite of the projects security-oriented goals to make such claims that are provably false, which we can agree is not an ideal quality when seeking a project that you can place trust in.

I am raising this issue since when I tried to point this out in my recently closed PR (_which is now locked_), I was dismissed at the time without a response that acknowledged the evidence provided. Perhaps there was a miscommunication?

The [pending revision](https://github.com/kanidm/kanidm/pull/2963) should probably tackle this update.

**History:**
- Nov 2019: [An issue](https://github.com/kanidm/kanidm/issues/139) opened to explain why TLS was required (_covered in [this comment regarding `secure` cookie](https://github.com/kanidm/kanidm/issues/138#issuecomment-550562726)_).
- The TLS requirement was documented and explained [in this PR](https://github.com/kanidm/kanidm/pull/143/files#diff-a6ccd4e2e190471add7134d079c23ed0fb894178871a960a3b3b84e817b729d3R4-R7)
  - Noting that TLS at the time was specifically needed for the secure cookie feature.
  - At this time there there was no strict TLS requirement for kanidm itself, only the client sending the request over HTTPS. I haven't checked the commit history since, but at some point this was altered to the current state that is inaccurate.

**Comment by polarathene** [comment]
## Evidence - Cookie `secure` attribute requires the client request to use HTTPS (not subsequent hops)

This seems a bit unnecessary, but I put it together due to [this feedback](https://github.com/kanidm/kanidm/pull/2950#issuecomment-2267423632), although I think that feedback was ignoring the context regarding TLS termination occurring prior to reaching kanidm.

**Context** - `secure` attribute for cookies:

> https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#block_access_to_your_cookies

> 
> _A cookie with the Secure attribute is only sent to the server with an encrypted request over the HTTPS protocol. It's never sent with unsecured HTTP (except on localhost), which means [man-in-the-middle](https://developer.mozilla.org/en-US/docs/Glossary/MitM) attackers can't access it easily._

### Reproduction

Here is a small rust example that can be used to test against:

```rust
use rocket::http::{Cookie, CookieJar};

// Send a request here with the `message=some-value` cookie to verify working support.
// NOTE:
// - HTTPS is required for clients to send cookies with the `Secure` attribute.
// - Requests to `http://localhost` is an exception where clients will send `Secure` cookies.
// - The exception does not apply to subdomains (http://example.localhost)
// - Only the client connection requires HTTPS. A reverse-proxy can terminate TLS and forward via HTTP.
//   This can also be seen via curl with an inline `--cookie` value which forces the `Set-Cookie` header to be sent.
#[rocket::get("/")]
fn read_cookie(jar: &CookieJar<'_>) -> String {
  match jar.get("message") {
    Some(cookie) => format!("Message: {}", cookie.value()),
    None => "Missing the message cookie".to_owned(),
  }
}

// Convenience route for a client to create the cookie:
#[rocket::post("/?<message>")]
fn create_cookie(jar: &CookieJar<'_>, message: Option<&str>) -> &'static str {
  let value = message.unwrap_or("This is a secure cookie!").to_owned();
  let cookie = Cookie::build(("message", value))
    .path("/")
    .secure(true)
    .http_only(true);

  // Add cookie to the jar for including in `Set-Cookie` response header
  jar.add(cookie);

  "Created the message cookie"
}

#[rocket::launch]
fn rocket() -> _ {
  rocket::build().mount("/", rocket::routes![read_cookie, create_cookie])
}
```

```console
$ cargo init /tmp/example-cookie && cd /tmp/example-cookie
$ cargo add rocket
# Replace the `src/main.rs` with the code above

# Default port rocket binds to is 8000, you can change via ENV `ROCKET_PORT=1234`
$ cargo run

# The `Set-Cookie` header is forced on the request:
$ curl --url http://example.localhost:8000 --cookie 'message=hello world'
Message: hello world

# This POST request will return a secure cookie to store at `/tmp/cookies.txt`
# NOTE: Change to `http://localhost` is required without TLS, otherwise Secure cookie will not be written.
$ curl --url http://localhost:8000 --cookie-jar /tmp/cookies.txt -X POST
Created the message cookie

# When curl performs the same request but instead provides `--cookie` a file path to a cookie-jar, the secure cookie
# `Set-Cookie` request header will only be set for HTTPS (with the exception of localhost above - but not it's subdomains)
$ curl --url http://example.localhost:8000 --cookie-jar /tmp/cookies.txt --cookie /tmp/cookies.txt
Missing the message cookie

$ curl --url http://localhost:8000 --cookie-jar /tmp/cookies.txt --cookie /tmp/cookies.txt
Message: This is a secure cookie!
```

### `compose.yaml`

You can copy/paste this `compose.yaml` config to the same project directory for the above reproduction.

This provides a quick way to run the above reproduction with a reverse proxy (Caddy) in front, which provides HTTPS while Docker provides the DNS resolver for `example.test` if you do not want to modify anything on the host.

```yaml
services:
  reverse-proxy:
    image: caddy:2.8
    container_name: caddy
    configs:
      - source: caddy-config
        target: /etc/caddy/Caddyfile
    # If wanting to reach from the host via `https://example.localhost`
    ports:
      - "80:80"
      - "443:443"
    # Containers on this network will resolve these aliases to the IP of this container:
    networks:
      default:
        aliases:
          - example.test

  # OPTIONAL: Build and run container.
  # NOTE: You could alternatively remove the builder stage and COPY a local static build instead.
  cookie-example:
    image: local/cookie-example:latest
    pull_policy: build
    build:
      # Dockerfile is only inlined for ease of trying this example via copy/paste:
      # Ensure the COPY files are present before building.
      # NOTE: `$$` is used below to opt-out of ENV compose interpolation feature.
      dockerfile_inline: |
        # syntax=docker/dockerfile:1

        FROM fedora AS builder
        RUN <<EOF
          dnf install -y rustup git-core gcc musl-gcc
          rustup-init -y --profile minimal --default-toolchain stable --target x86_64-unknown-linux-musl
        EOF

        ENV PATH "/root/.cargo/bin:/root/.cargo/env:$${PATH}"
        ARG RUSTFLAGS="-C strip=symbols -C relocation-model=static -C target-feature=+crt-static"
        ARG CARGO_TARGET_DIR=/build/target
        #ARG CARGO_BUILD_TARGET=x86_64-unknown-linux-musl
        WORKDIR /build

        COPY Cargo.toml Cargo.lock .
        COPY src/main.rs src/main.rs
        RUN --mount=type=cache,target=$${CARGO_TARGET_DIR} <<EOF
          cargo build --release --target x86_64-unknown-linux-musl
          mv "$${CARGO_TARGET_DIR}/x86_64-unknown-linux-musl/release/example-cookie" /build/app
        EOF

        # Minimal image
        FROM scratch
        COPY --link --from=builder /build/app /app
        ENV ROCKET_ADDRESS 0.0.0.0
        ENV ROCKET_PORT 80
        ENTRYPOINT ["/app"]

# OPTIONAL: Provides predicatable subnet and easier to join other containers to the same network.
networks:
  default:
    name: custom-network
    ipam:
      driver: default
      config:
        - subnet: "172.16.42.0/24"

# Alternative to separate files via `volumes`. Embeds the Caddyfile content within the `compose.yaml`.
configs:
  caddy-config:
    content: |
      # This block will handle both domains with automatic HTTP => HTTPS redirection,
      # Use example.localhost if querying from Docker host, otherwise example.test within containers:
      example.localhost, example.test {
        # Self-signed certs generated instead of LetsEncrypt provisioned:
        tls internal
        # Alternatively provide path to your own:
        #tls /path/to/cert.pem /path/to/key.pem

        # Caddy terminates TLS, traffic forwarded to this service over HTTP:
        reverse_proxy cookie-example:80
        # Alternatively forward traffic to host if not running the cookie-example service via container:
        # reverse_proxy host.docker.internal:80
      }
```

Start those two containers and join that docker network with another for running curl:

```console
$ docker compose up --force-recreate
$ docker run --rm -it --network custom-network alpine
$ apk add curl

# Get the cookie stored:
$ curl --insecure --url https://example.test --cookie-jar /tmp/cookies.txt -X POST
Created the message cookie
# Make a request with cookie:
$ curl --insecure --url https://example.test --cookie /tmp/cookies.txt
Message: This is a secure cookie!
```
