### ISSUE TITLE
LDAP sync is broken

### ISSUE THREAD

**Issue by Samonitari** [kanidm/kanidm#3039]
### I did this

I've successfully synced my LDAP accounts before, initially about a year ago. Synced accounts can be used with same password. Sync is not yet finalized.
I've upgraded to newer version with SCIM parts in, and now sync won't run successfully.

### Kanidm version details

- Output of `kanidm(d) version`: 1.4.0-dev (1.4.0~dev~git24.9f4cc98-lp155.1.2
- If not a container, how'd you install it: from obs://build.opensuse.org/home:firstyear
- Operating System / Version (On Unix please post the output of `uname -a`): Linux example.com 5.14.21-150500.55.73-default #1 SMP PREEMPT_DYNAMIC Tue Aug 6 15:51:33 UTC 2024 (a0ede6a) x86_64 x86_64 x86_64 GNU/Linux

### Any other comments

I've tried removig the jpegPhoto LDAP attribute.
Debugging the sync it seems fails on person entries, like this (sanitized, but tried to keep "features" like more interesting chars)

``` json5
2024-09-13T14:26:09.885427Z DEBUG kanidm_ldap_sync: LdapSyncReplEntry {
    entry_uuid: 6a22e9f0-ea80-103c-887d-4d1b4203daaf,
    state: Add,
    entry: LdapEntry {
        dn: "uid=username1,ou=people,dc=mydomain.tld,dc=examplehosting",
        attrs: {
            "cn": {
                "Givennameone Givennametwo LongerFamilyNameWithé Familynamewithéandá",
            },
            "createtimestamp": {
                "20221027201933Z",
            },
            "creatorsname": {
                "cn=admin,dc=examplehosting",
            },
            "entrycsn": {
                "20240913140402.810820Z#000000#000#000000",
            },
            "entrydn": {
                "uid=username1,ou=people,dc=mydomain.tld,dc=examplehosting",
            },
            "entryuuid": {
                "6a22e9f0-ea80-103c-887d-4d1b4203daaf",
            },
            "givenname": {
                "Givennametwo",
                "Givennameone",
            },
            "hassubordinates": {
                "FALSE",
            },
            "mail": {
                "username1@mydomain.tld",
            },
            "mailalias": {
                "alias1@mydomain.tld",
                "al.i.as2@mydomain.tld",
            },
            "memberof": {
                "uid=randomgroup,ou=groups,dc=mydomain.tld,dc=examplehosting",
            },
            "modifiersname": {
                "uid=someuser,ou=people,dc=mydomain.tld,dc=examplehosting",
            },
            "modifytimestamp": {
                "20240913140402Z",
            },
            "objectclass": {
                "inetorgperson",
                "nextcloudaccount",
                "organizationalperson",
                "person",
                "postfixbookmailaccount",
                "top",
            },
            "pwdchangedtime": {
                "20230607172213Z",
            },
            "pwdhistory": {
                "20221113084006Z#1.3.6.1.4.1.1466.115.121.1.40#105#{ARGON2}$argon2id$v=19$m=65536,t=8,p=1$57FF/rgolY/nlasdZ85Muw$vLkI9LMKr5FtTt9b5gg0jpFrFfMRSwt5JsUD9ynuO+w",
                "20230607172213Z#1.3.6.1.4.1.1466.115.121.1.40#105#{ARGON2}$argon2id$v=19$m=65536,t=8,p=1$y+DUwY9l0pSasdoPz8t3rg$YvLR7hGJc0Bwwegrm/7IWk2Ngfn94Ffl9BGw3db7Qrg",
            },
            "receivemailalias": {
                "receivealias1@mydomain.tld",
                "receive.alias2@mydomain.tld",
            },
            "sn": {
                "LongerFamilyNameWithé Familynamewithéandá",
            },
            "structuralobjectclass": {
                "inetOrgPerson",
            },
            "subschemasubentry": {
                "cn=Subschema",
            },
            "telephonenumber": {
                "+123445464677",
            },
            "uid": {
                "username1",
            },
            "userpassword": {
                "{ARGON2}$argon2id$v=19$m=65536,t=8,p=1$oWKPCLQ/H/qSMC/axDcMQQ$/0sWej+Hl34Knzp3+JZqoAm8tZAJuA0yix8M6UOpWwU",
            },
        },
    },
}
```

Error (error message is wrong, as it's a person object sync step, but the same message is used in source:
`2024-09-13T14:26:09.885564Z ERROR kanidm_ldap_sync: Unable to convert group to scim_sync_group json_err=Error("data did not match any variant of untagged enum ScimValue", line: 0, column: 0)`

ldap-sync.toml:
``` toml
# The sync account token as generated by "system sync generate-token".
sync_token = "iwontgiveyouthis"
ldap_uri = "ldaps://ldap.example.tld"

# ugly hack - copied cert
ldap_ca = "/tmp/cert7.pem"

max_ber_size = 1310720
ldap_sync_dn = "cn=kanidm,ou=services,dc=common,dc=examplehosting"
ldap_sync_pw = "ialsowontgiveyouthis"
ldap_sync_base_dn = "dc=example.tld,dc=examplehosting"
ldap_filter = "(|(objectclass=person)(objectclass=groupOfNames))"
person_attr_user_name = "uid"
person_attr_display_name = "cn"
person_attr_mail = "mail,mailAlias"
person_attr_password = "userpassword"

# If the password value requires a prefix for Kanidm to import it, this can be optionally
# provided here.
#
# person_password_prefix = ""
group_attr_name = "uid"
group_attr_description = "cn"

# some user
[502d69d6-ea34-189a-887c-4d0a4203daaf]
map_loginshell = "/bin/zsh"
```
