### ISSUE TITLE
Handle replication DNS resolution in Kubernetes 

### ISSUE THREAD

**Issue by pando85** [kanidm/kanidm#3188]
### I did this

Deployed multiple replicas in a StatefulSet in a Kubernetes environment. I used the [Pod subdomain](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) for referring to each replica.

#### Configuration example

Pod 0:
```toml
[replication]
origin = "repl://test-change-kanidm-replicas-default-0.test-change-kanidm-replicas:8444"
bindaddress = "0.0.0.0:8444"

[replication."repl://test-change-kanidm-replicas-default-1.test-change-kanidm-replicas:8444"]
type = "mutual-pull"
partner_cert = "****"
automatic_refresh = false
```

Pod 1:
```toml
[replication]
origin = "repl://test-change-kanidm-replicas-default-1.test-change-kanidm-replicas:8444"
bindaddress = "0.0.0.0:8444"

[replication."repl://test-change-kanidm-replicas-default-0.test-change-kanidm-replicas:8444"]
type = "mutual-pull"
partner_cert = "****"
automatic_refresh = false
```

### I expected the following

Replication works bidirectionally between different pods.

### This happened instead

Replicas try to connect to the IP resolved when they start. So, just the last restarted replica will work because pods get a different IP when recreated.

### Kanidm version details

- Output of `kanidm(d) version`:  `kanidmd 1.4.2`
- Are you running it in a container? If so, which image/tag?: Yes, kanidm/server:latest

### Any other comments

You can workaround it by forcing a restart of the process but it is not the intended way of working in Kubernetes and when a node is down or you just have to change some configuration, Pod will be recreated.
