### ISSUE TITLE
Sync from openldap using crypt password scheme

### ISSUE THREAD

**Issue by pmarr** [kanidm/kanidm#3457]
### I did this

```shell
 podman run --rm -it --name kanidm-ldap-sync-run \
      --network host \
      --userns auto --user 1000:1000 \
      -v ./kanidm-client-config:/etc/kanidm/config:ro,U \
      -v ./ldap-sync-config:/etc/kanidm/ldap-sync:ro,U \
      -v ./chain.pem:/chain.pem:ro,U \
      kanidm/tools:1.5.0 kanidm-ldap-sync -c /etc/kanidm/config
```
On a single entry against a very old openldap 2.4.X (RHEL 6.4 era) instance still using the 34-byte MD5 hash {crypt} scheme: `{crypt}$1$YkVwSR...snip`. 

ldap-sync-config:
```toml
ldap_uri = "ldaps://ldap.example.com"
ldap_ca = "/chain.pem"
ldap_sync_dn = "cn=replica,ou=system,dc=ldap,dc=example,dc=com"
ldap_sync_base_dn = "dc=ldap,dc=example,dc=com"
ldap_filter = "(uid=user1)"
# actual filters for full sync
#ldap_filter = "(& (|(objectClass=groupOfNames)(objectClass=posixGroup)(objectClass=person)(objectClass=inetOrgPerson)) (!(ou:dn:=xsede))(!(ou:dn:=PendingAccounts))(!(ou:dn:=DisabledAccounts)))"

# Just users
#ldap_filter = "(& (|(objectClass=person)(objectClass=inetOrgPerson)) (!(ou:dn:=xsede))(!(ou:dn:=PendingAccounts))(!(ou:dn:=DisabledAccounts)))"

# Just groups
#ldap_filter = "(& (|(objectClass=groupOfNames)(objectClass=posixGroup)) (!(ou:dn:=xsede))(!(ou:dn:=PendingAccounts))(!(ou:dn:=DisabledAccounts)))"

person_objectclass = "inetorgperson"
person_attr_user_name = "uid"
person_attr_display_name = "cn"
person_attr_gidnumber = "uidnumber"
person_attr_login_shell = "loginshell"
person_attr_password = "userpassword"

group_objectclass = "posixgroup"
group_attr_name = "cn"
group_attr_description = "description"
group_attr_member = "memberuid"
group_attr_gidnumber = "gidnumber"
```

### I expected the following

Either the {crypt} password to be imported.

After looking at: https://github.com/kanidm/kanidm/blob/master/libs/crypto/src/lib.rs I see only SSHA*, ARGON2 and PBKDF2 are supported. So I imagine the sync should never successfully pull these `{crypt}` passwords in.

I also expected he attribute mappings to be camelCase. They are lowercase in the above mapping, but the fields like `memberUid` or `userPassword` are camelCase in the openldap instance. Making the attributes camelCase here will actually syncs the users but without any of the cameCase defined attributes.

### This happened instead

Debug logs from kanidmd show `7a9f763a-8428-4104-ba72-1800c21b33f5 ERROR    │        │  │     ┕━ 🚨 [error]: password_import was unable to convert hash format | hint: {cry | entry_id: user1`
```
7a9f763a-8428-4104-ba72-1800c21b33f5 INFO     request [ 1.51ms | 7.81% / 100.00% ] method: POST | uri: /scim/v1/Sync | version: HTTP/1.1
...<snip>...
7a9f763a-8428-4104-ba72-1800c21b33f5 INFO     │     ┕━ scim_sync_apply_phase_3 [ 151µs | 5.33% / 9.95% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        ┝━ 🐛 [debug]: Schemas valid - Proceeding with entry f6cf0112-4567-1038-89b1-7bf7bf6abb46
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        ┝━ 🐛 [debug]:  | requested_classes: {"account": SchemaClass { name: "account", uuid: 00000000-0000-0000-0000-ffff00000046, descriptio
n: "Object representation of an account", sync_allowed: true, systemmay: [AccountExpire, AccountValidFrom, NameHistory], may: [], systemmust: [DisplayName, Name, Spn], must: [], systemsuppl
ements: ["oauth2_resource_server", "person", "service_account"], supplements: [], systemexcludes: [], excludes: [] }, "person": SchemaClass { name: "person", uuid: 00000000-0000-0000-0000-f
fff00000044, description: "Object representation of a person", sync_allowed: true, systemmay: [ApplicationPassword, AttestedPasskeys, CredentialUpdateIntentToken, LegalName, Mail, OAuth2Con
sentScopeMap, OAuth2Session, PassKeys, PrimaryCredential, RadiusSecret, SshPublicKey, UserAuthTokenSession], may: [], systemmust: [IdVerificationEcKey], must: [], systemsupplements: [], sup
plements: [], systemexcludes: ["application", "service_account"], excludes: [] }, "posixaccount": SchemaClass { name: "posixaccount", uuid: 00000000-0000-0000-0000-ffff00000057, description
: "Object representation of a posix account, requires account", sync_allowed: true, systemmay: [LoginShell, UnixPassword], may: [], systemmust: [GidNumber], must: [], systemsupplements: ["a
ccount"], supplements: [], systemexcludes: [], excludes: [] }}
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        ┝━ 🐛 [debug]:  | sync_owned_attrs: {AccountExpire, AccountValidFrom, AttestedPasskeys, DisplayName, GidNumber, LegalName, LoginShell,
 Mail, Name, NameHistory, PassKeys, PasswordImport, PrimaryCredential, RadiusSecret, SshPublicKey, TotpImport, UnixPasswordImport}
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        ┝━ batch_modify [ 70.0µs | 1.66% / 4.62% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  ┝━ impersonate_search_valid [ 14.1µs | 0.10% / 0.93% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │  ┕━ search [ 12.5µs | 0.23% / 0.82% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │     ┝━ be::search [ 1.95µs | 0.13% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │     │  ┕━ 🐛 [debug]:  | search_filter_executed_plan: EqIndexed(uuid)
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │     ┕━ access::filter_entries [ 7.00µs | 0.46% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │        ┕━ 🐛 [debug]: allowed search of 1 entries ✅
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  ┝━ access::batch_modify_allow_operation [ 15.6µs | 1.03% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │  ┝━ 🐛 [debug]: Requested present set | requested_pres: {Class, DisplayName, GidNumber, LoginShell, Mail, Name, PasswordImport, S
yncClass}
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │  ┝━ 🐛 [debug]: Requested remove set | requested_rem: {AccountExpire, AccountValidFrom, AttestedPasskeys, DisplayName, GidNumber,
 LegalName, LoginShell, Mail, Name, NameHistory, PassKeys, PrimaryCredential, RadiusSecret, SshPublicKey}
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │  ┝━ 🐛 [debug]: Requested class set | requested_classes: {"account", "person", "posixaccount"}
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │  ┝━ 🐛 [debug]:  | entry_id: f6cf0112-4567-1038-89b1-7bf7bf6abb46
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │  ┕━ 🐛 [debug]: allowed modify of 1 entries ✅
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  ┝━ plugins::run_pre_batch_modify [ 15.3µs | 0.35% / 1.01% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │  ┝━ protected_pre_batch_modify [ 307ns | 0.02% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │  ┝━ base_pre_modify [ 752ns | 0.05% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │  ┝━ base_pre_modify [ 767ns | 0.05% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 DEBUG    │        │  │  ┕━ password_import_pre_batch_modify [ 8.07µs | 0.53% ]
7a9f763a-8428-4104-ba72-1800c21b33f5 ERROR    │        │  │     ┕━ 🚨 [error]: password_import was unable to convert hash format | hint: {cry | entry_id: user1
7a9f763a-8428-4104-ba72-1800c21b33f5 ERROR    │        │  ┕━ 🚨 [error]: Pre-Modify operation failed (plugin), Plugin(CredImport("password_import was unable to convert hash format")) | even
t_tag_id: 1
7a9f763a-8428-4104-ba72-1800c21b33f5 ERROR    │        ┕━ 🚨 [error]: Unable to apply modifications to sync entries. | err: Plugin(CredImport("password_import was unable to convert hash for
mat"))
7a9f763a-8428-4104-ba72-1800c21b33f5 ERROR    ┝━ 🚨 [error]:  | latency: 1.514444ms | status_code: 500 | kopid: "7a9f763a-8428-4104-ba72-1800c21b33f5" | msg: "error handling request"
7a9f763a-8428-4104-ba72-1800c21b33f5 ERROR    ┕━ 🚨 [error]: response failed | classification: Status code: 500 Internal Server Error | latency: 1 ms
```
### Kanidm version details

- Output of `kanidm(d) version`: 
```
kanidmd version # server
kanidmd 1.5.0

#client
podman run --rm -it -v ./kanidm-client-config:/root/.config/kanidm:ro -v ./client-tokens:/root/.cache/kanidm_tokens:rw,U --name kanidm-client --network host --userns auto kanidm/tools:1.5.0 kanidm version
kanidm 1.5.0
```
- Are you running it in a container? If so, which image/tag?: Yes
```
docker.io/kanidm/tools                       1.5.0       974563702785  13 days ago   599 MB
docker.io/kanidm/server                      1.5.0       0d4174103e94  13 days ago   740 MB
```

- Operating System / Version (On Unix please post the output of `uname -a`): RHEL 8
`Linux idm.example.com 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Any other comments

I'm investigating migrating our sites' LDAP backends to a more modern and ergonomic IdM. The first class posix auth support, a pam module to go with it, and a memory safe language sound absolutely delightful.

Is there a way to get this sync to pass so I can force users to recreate passwords on the kanidm side? I.e. ignore the userPassword field for every entry (Some 6000 of them). I don't really want md5 to be a supported password hashing scheme.

I'd love to switch our hpc systems to Kanidm but I'm struggling to find a clear migration path forward short of scripting out the user's passwords and replacing with dummy hashes.

Thank you for all the work that's been put into this software. For the longest time, cruft and homebrew on top of ldap is all we've had for our clusters of unix servers.
