### ISSUE TITLE
[kanidmd] Support config file arg before subcommand

### ISSUE THREAD

**Issue by tennox** [kanidm/kanidm#3561]
### Is your feature request related to a problem? Please describe

I'm trying to set up kanidm in a docker environment, and wanted the config file in a different volume than the data:
```
services:
  # from: https://kanidm.github.io/kanidm/stable/examples/traefik.html?highlight=reverse#traefik
  kanidm:
    container_name: kanidm
    image: kanidm/server:1.5.0
    restart: always # `unless-stopped` is a bad example btw.
    command: [ "/sbin/kanidmd", "server", "-c", "/config/server.toml"] # adapt config file location - https://github.com/kanidm/kanidm/blob/master/server/Dockerfile#L108C1-L109C60
    volumes:
      - ./server.toml:/config/server.toml:ro
      - ./data:/data
      - ./certs:/certs:ro
```

and wanted to add a helper script to execute kandimd commands:
```bash
#!/usr/bin/env bash
set -euxo pipefail

docker compose exec kanidm kanidmd -c /config/server.toml "$@"
```

But that fails:
```
❯ ./kanidmd --help
+ docker compose exec kanidm kanidmd -c /config/server.toml --help
error: unexpected argument '-c' found
```
If I pass the config file afterwards, it works:
```
❯ dc exec kanidm kanidmd recover-account -c /config/server.toml admin
📜 Using config file: "/config/server.toml"
```

### Describe the solution you'd like

Allow passing `-c` arg before subdommand

### Describe alternatives you've considered

Pass config file location as environment variable.
