### ISSUE TITLE
kanidmd: Enabling `otel_grpc_url` enables a second logging stack that ignores `log_level`

### ISSUE THREAD

**Issue by jinnatar** [kanidm/kanidm#3703]
### I did this
With config version 2, Enabled the `otel_grpc_url` setting to get tracing data. At the same time my `log_level` is set to `info`.

### I expected the following
- Receive traces
- Receive logs at `INFO` level. 

### This happened instead
- Receive traces just fine (although super high volume due to `handle_repl_conn`, but that's another issue)
- Receive logs at `DEBUG` level, and INFO level is duplicated with two different formats.

### Kanidm version details

- Output of `kanidm(d) version`: `kanidmd 1.6.4`
- Are you running it in a container? If so, which image/tag?: Yes, `kanidm/server:1.6.4`
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`):

### Any other comments

I _think_ what's going on here is that enabling otel tracing somehow enables a second logging stack in parallel, or at least a different channel for it. Looking at the logging (a bit further down), some messages at INFO are actually logged twice. Small sample:
> 2025-06-28T06:25:27.997039Z  INFO kanidmd: Starting Kanidmd version=1.6.4
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Starting Kanidmd | version: 1.6.4

Full slightly redacted config for reference as snapshotted from one node:
```toml
version = "2"

bindaddress = "[::]:8443"
ldapbindaddress = "[::]:3636"

db_path = "/data/db/kanidm.db"
db_fs_type = "other"

otel_grpc_url = "http://10.0.10.5:4317"

tls_chain = "/data/chain.pem"
tls_key = "/data/key.pem"

log_level = "info"

domain = "idm.example.com"
origin = "https://idm.example.com"

[http_client_address_info]
x-forward-for = ["10.0.10.2", "10.0.10.3", "10.0.10.4", "10.0.10.5", "10.0.10.6"]
[ldap_client_address_info]
proxy-v2 = ["10.0.10.2", "10.0.10.3", "10.0.10.4", "10.0.10.5", "10.0.10.6"]


[online_backup]
path = "/data/backups/"
schedule = "00 22 * * *"
versions = 7


[replication]
origin = "repl://10.0.10.5:8445"
bindaddress = "0.0.0.0:8445"


[replication."repl://10.0.10.2:8445"]
type = "mutual-pull"
partner_cert = "MIIB-x"
automatic_refresh = false

[replication."repl://10.0.10.3:8445"]
type = "mutual-pull"
partner_cert = "MIIB-x"
automatic_refresh = false

[replication."repl://10.0.10.4:8445"]
type = "mutual-pull"
partner_cert = "MIIB-x"
automatic_refresh = false
```

Startup logging with that config but different node, STDERR:
> 📜 Using config file: "/secrets/server.toml"

STDOUT:
> 2025-06-28T06:25:27.997039Z  INFO kanidmd: Starting Kanidmd version=1.6.4
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Starting Kanidmd | version: 1.6.4
2025-06-28T06:25:27.997376Z DEBUG kanidmd: Acquired kanidm exclusive lock
2025-06-28T06:25:27.997407Z  INFO kanidmd: Running in server mode ...
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Running in server mode ...
2025-06-28T06:25:27.997512Z  INFO kanidmd_core: Starting kanidm with configuration: address: [::]:8443, domain: idm.example.com, ldap address: [::]:3636, origin: https://idm.example.com admin bind path: /data/kanidmd.sock, thread count: 1, dbpath: /data/db/kanidm.db, arcsize: AUTO, max request size: 262144b, http client address info: x-forward-for [ 10.0.10.2 10.0.10.3 10.0.10.4 10.0.10.5 10.0.10.6 ], ldap client address info: proxy-v2 [ 10.0.10.2 10.0.10.3 10.0.10.4 10.0.10.5 10.0.10.6 ], with TLS: true, online_backup: enabled: true - schedule: 00 22 * * * versions: 7 path: /data/backups/, integration mode: false, console output format: Text log_level: inforole: write replica, replication: enabledrepl_origin: repl://10.0.10.2:8445 repl_address: 0.0.0.0:8445 integration repl config mode: false, otel_grpc_url: Some("http://10.0.10.2:4317")
00000000-0000-0000-0000-000000000000 INFO     ｉ [info]: Starting kanidm with configuration: address: [::]:8443, domain: idm.example.com, ldap address: [::]:3636, origin: https://idm.example.com admin bind path: /data/kanidmd.sock, thread count: 1, dbpath: /data/db/kanidm.db, arcsize: AUTO, max request size: 262144b, http client address info: x-forward-for [ 10.0.10.2 10.0.10.3 10.0.10.4 10.0.10.5 10.0.10.6 ], ldap client address info: proxy-v2 [ 10.0.10.2 10.0.10.3 10.0.10.4 10.0.10.5 10.0.10.6 ], with TLS: true, online_backup: enabled: true - schedule: 00 22 * * * versions: 7 path: /data/backups/, integration mode: false, console output format: Text log_level: inforole: write replica, replication: enabledrepl_origin: repl://10.0.10.2:8445 repl_address: 0.0.0.0:8445 integration repl config mode: false, otel_grpc_url: Some("http://10.0.10.2:4317")
2025-06-28T06:25:28.068850Z DEBUG kanidmd_core::crypto: The RSA private key size is: 2048 bits, that's OK!
2025-06-28T06:25:28.069175Z DEBUG schema::generate_in_memory: kanidmd_lib::schema: schema validate -> passed event_tag_id=0
2025-06-28T06:25:28.069313Z DEBUG be::new: kanidmd_lib::be: db_tickets=1 profile=container_generic cpu_flags=x86_64_v2
2025-06-28T06:25:28.127365Z DEBUG kanidmd_lib::server: Server UUID -> d7x
2025-06-28T06:25:28.127390Z DEBUG kanidmd_lib::server: Domain UUID -> 79x
2025-06-28T06:25:28.127394Z DEBUG kanidmd_lib::server: Domain Name -> "idm.example.com"
2025-06-28T06:25:28.127576Z DEBUG system_initialisation: kanidmd_lib::be: upgrade_reindex event_tag_id=0 dbv=32 v=32
