### ISSUE TITLE
Possibility to set `server_name` from config

### ISSUE THREAD

**Issue by erictapen** [kanidm/kanidm#616]
Currently (current master 0f4189a57ef9fb0f048cd2cc3f5eee3d132adbd1) it doesn't seem possible to set `server_name` from config, resulting in startup errors like this:

```
kanidmd[919]: 00000000-0000-0000-0000-000000000000 2021-11-24T02:27:40.841254897+00:00 ERROR    🚨 [admin.error]: Effective domain is not a descendent of server domain name (rp_id). You must change origin or domain name to be consistent. ed: "https://idm.acme.test" - rp_id: "example.com"
kanidmd[919]: [kanidm::core] Unable to setup query server or idm server -> InvalidState
```

server.toml:

```toml
bindaddress = "[::1]:8443"
db_path = "/var/lib/kanidm/kanidm.db"
# this setting doesn't seem to have an effect but maybe would be a good place for specifying it?
domain_name = "acme.test"
log_level = "default"
origin = "https://idm.acme.test"
role = "WriteReplica"
```

My current workaround is patching the source:

```patch
diff --git a/kanidmd/src/lib/plugins/domain.rs b/kanidmd/src/lib/plugins/domain.rs
index 7e1797f2..15b8737d 100644
--- a/kanidmd/src/lib/plugins/domain.rs
+++ b/kanidmd/src/lib/plugins/domain.rs
@@ -39,7 +39,7 @@ impl Plugin for Domain {
                 trace!("plugin_domain: Applying uuid transform");
                 // We only apply this if one isn't provided.
                 if !e.attribute_pres("domain_name") {
-                    let n = Value::new_iname("example.com");
+                    let n = Value::new_iname("acme.test");
                     e.set_ava("domain_name", btreeset![n]);
                     trace!("plugin_domain: Applying domain_name transform");
                 }


```

I find it a bit unintuitive to have `example.com` be a default value, this is probably not intended?
